services:
  database:
    image: mariadb:latest
    container_name: elysium-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ertUIbd93"
      MYSQL_DATABASE: "elysiumDatabase"
      MYSQL_USER: "userAdmin"
      MYSQL_PASSWORD: "1234"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - elysium-db-data:/var/lib/mysql
    networks:
      - elysium-network

  backend:
    build: ./backend
    container_name: elysium-backend
    ports:
      - "3000:3000"
    environment:
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}

    - PORT=${PORT}

    - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
    - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

    - userSenderEmail=${userSenderEmail}
    - apiKeyUserSenderEmail=${apiKeyUserSenderEmail}

    - urlUserNormal=${urlUserNormal}
    - urlUserEnterprise=${urlUserEnterprise}

    - levelSegurityDefault=${levelSegurityDefault}
    depends_on:
      - database
    networks: 
      - elysium-network

  client:
    build: ./client
    container_name: elysium-client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - elysium-network

  services:
  ollama:
    image: ollama/ollama:0.6.8
    container_name: elysium-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - elysium-network
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 5 &&
      ollama list | grep llama3.1:8b || ollama pull llama3.1:8b &&
      wait
      "

networks:
  elysium-network:
    driver: bridge

volumes:
  elysium-db-data:
  ollama-data:
